aduros/wasm4

cli/lib/png2src.js
This PR adjusts the code generate by `png2src --rust` to conform to the idiom that `static` and `const` variable name should have a [SCREAMING_SNAKE_CASE](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html?highlight=SCREAMING_SNAKE_CASE#accessing-or-modifying-a-mutable-static-variable). Current output when running `cargo check` with the generated code produces the following warnings.
```
Checking cart v0.1.0 (/home/rfm/projects/a-bit-rowdy)
warning: constant `png_name_width` should have an upper case name
--> src/sprites.rs:1:11
|
1 | pub const png_name_width: u32 = 48;
|           ^^^^^^^^^^^^^^ help: convert the identifier to upper case: `PNG_NAME_WIDTH`
|
= note: `#[warn(non_upper_case_globals)]` on by default
warning: constant `png_name_height` should have an upper case name
--> …
```
=> png2src --rust should conform to rust style guide

cli/assets/templates/rust/src/wasm4.rs
Parameter stride is a width, it cannot be negative.
=> Change stride type to u32 in Rust template blit_sub function

.gitignore, site/.gitignore
Moves .gitignore declaration of `node_modules`  and oher commonly ignored files from `site/node_modules` to `<repo-root>/.gitignore`
`node_modules` are commonly ignored via a  `.gitignore` set at the repository root directory.
It prevents accidental commits of node_modules and simplify the development of PRs.
=> [git]: prevent accidental commits of `cli/node_modules` or `runtimes/web/node_modules`

cli/cli.js, cli/lib/png2src.js, site/docs/guides/sprites.md
Png2src is good, but code had a hardcoded switch-bassed generators for specific language.
I reformat code to string-tempates, now very easy add another source generators.
Other feature - custom templates, you can generate a game-specific source, for example:
```
export const %name% = {
width: %width%,
height: %height%,
flags: %flags%,
data: memory.data<u8>([ %bytes% ])
};
```
This template will emit a object export for AssemblyScript instead of constants, simmilar Trait/Object/Struct can be generated and for Rust/Go/C.
Guide for custom template is added also.
PS:
i use a template for AS like this:
```
import { Frame } from "../nodes/sprite";
const %name% = memory.data<u8>([ %bytes% ]);
export const %name%Frame = new Frame(%width%, %height%, %name%, %flags%);
```
=> [png2src] Improvements, support custom templates

cli/lib/png2src.js
In templates, "width" got replaced by "height" instead of the width.
=> Fixed small error in png2src

runtimes/web/src/apu.js
AudioContext for old IOS is branded
Fix #84
=> Fix AudioContext

runtimes/web/src/index.js
Realted: #24, #73
Use a implementation from:
https://gist.github.com/addyosmani/5434533#file-limitloop-js-L60
how to check?
Run chrome without v-sync:
https://gist.github.com/brunosimon/c15e7451a802fa8e34c0678620022f7d
Open any game.
Video:  https://youtu.be/VxCclCHjwII
LEFT- fixed, RIGHT - current
=> fix: reduce framerate onto 60 FPS

cli/cli.js, cli/lib/new.js, cli/lib/png2src.js
Setting the env var "W4_LANG" changes the default value for "new" and "png2src".
For this, a new option was added: "--lang".
This option can only have these options:
- as
- assemblyscript
- c
- rs
- rust
- go
In case no value was provided by either env or cli,
it falls back to "as".
It can still be overriden by using the options --as etc.
Examples:
```bash
w4 new snake # Creates "snake" using AssemblyScript
w4 new --go snake # Creates "snake" using Go
W4_LANG=go w4 new snake # Creates "snake" using Go
W4_LANG=go w4 new --rust snake # Creates snake using Rust
```
The same is true for `png2src`.
=> Setting default language using env vars

cli/cli.js
In essence a "w4 init" is an alias to "w4 new ."
To achieve this and reduce code duplication, I've created a new
function called "blankProject" inside cli.js.
It takes a program.command and attaches the options of the "new" command
This function then is called for "new" and "init".
To make it a bit simpler still, I've also added a "real" alias to
"new" called "create".
Further "changes"to the source code are due to auto-formatting it.
// Edit: Yay, another low-hanging fruit solved!
=> Added "w4 init" - Fixes #50

runtimes/web/src/index.js
Fix #104 
Support native gamepad.
Now only first gamepad is used.
DPAD + LEFT AXIS - movement
X, O (DS4 mapping) - X, Z
LEFT/RIGHT Triggers - X, Z
Sometimes joys swap a buttons order for right buttons panel, need investigate this case.
This is feature a runtime, this means that need rebundle games.
UPD:
If you trigger a keyboard or gamepad in game - last input device will be used. You can change gamepad/keyboard on fly.
First connected gamepad is used on multiple gamepad system , and replaced on latest available after disconnection.
=> feat: Gamepad

site/docs/guides/basic-drawing.md
Adds missing framebuffer manipulation examples written in rust.
related #96
=> docs(rust): add rust examples in basic-drawing.md

site/docs/guides/saving-data.md
Adds missing rust examples to the saving-data.md
=> docs: add rust examples to saving-data.md

cli/assets/templates/assemblyscript/src/wasm4.ts, cli/assets/templates/c/src/wasm4.h, cli/assets/templates/go/w4/wasm4.go, cli/assets/templates/rust/src/wasm4.rs, cli/package-lock.json, runtimes/web/src/framebuffer.js, runtimes/web/src/runtime.js, site/docs/reference/functions.md
This PR adds hline and vline functions and closes #74
```typescript
@external("env", "hline")
export declare function hline (x: i32, y: i32, len: i32): void;
```
Draws a horizontal line from `(x;y)`.
If `len` is greater than `0` draws from `(x; y)` to `(x + len; y)` excluded.
if `len` is lower than `0` draws from `(x + len + 1; y)` to `(x + 1; y)` excluded.
```typescript
@external("env", "vline")
export declare function vline (x: i32, y: i32, len: i32): void;
```
Draws a vertical line from `(x;y)`.
If `len` is greater than `0` draws from `(x; y)` to `(x; y + len)` excluded.
if `len` is lower than `0` draws from `(x; y + len + 1)` to `(x; y + 1)` excluded.
=> feat(framebuffer): add hline and vline functions

runtimes/web/src/framebuffer.js
Fix: #13 
Hah, oval has bug - It sometime skip lines (include a outline)
test:
```typescript
import * as w4 from "./wasm4";
let sx: u32 = 4;
let sy : u32 = 4;
let last: u32 = 0;
export function update (): void {
const gamepad = load<u8>(w4.GAMEPAD1);
const press = gamepad;// & (gamepad ^ last);
last = gamepad;
if((press & w4.BUTTON_LEFT) !== 0) {
sx --;
}
if((press & w4.BUTTON_RIGHT) !== 0) {
sx ++;
}
if((press & w4.BUTTON_UP) !== 0) {
sy --;
}
if((press & w4.BUTTON_DOWN) !== 0) {
sy ++;
}
store<u16>(w4.DRAW_COLORS, 0x2);
w4.text ("New Rect", 4, 4);
w4.text ("O:" + sx.toString() + ',' + sy.toString(), 84, 4);
store<u16>(w4.DRAW_COLORS, 0x32);
w4.rect (4, 12, sx + 1, sy + 1);
w4.oval (80 + 4, 12, sx + 1, sy + 1);
}
```
=> Refact Rect and Oval onto  vline/hline + oval fill

cli/assets/templates/rust/Cargo.toml, examples/pong/.cargo/config.toml, examples/pong/Cargo.toml, examples/pong/src/lib.rs
Bumps edition in rust starting template and pong example to `2021`.
- chore: update .cargo/config.toml in pong
- refactor: remove unnecessary unsafe block
- https://doc.rust-lang.org/edition-guide/rust-2021/index.html
- https://doc.rust-lang.org/edition-guide/editions/index.html
- https://blog.rust-lang.org/2021/05/11/edition-2021.html
=> bump rust edition to 2021

cli/cli.js, cli/lib/png2src.js, site/docs/guides/sprites.md
For more complex templates it makes sense to use a more feature-rich
template engine.
Since mustache was already a dependency, I converted
all templates to mustache.
I've also added the ability to output directly to a file instead to
Stdout.
=> Changed png2src template to mustache

site/docs/reference/cli.md, site/sidebars.js
A new page in the references to provide an overview of all possible commands of the `w4` CLI.
Each command is divided into those sections:
- Summary
- Usage
- Examples
- Table of options
- A more in-depth description of the command
The last point also includes setting up how to set default values (if possible).
I've also pointed out if the command has certain requirements (like png2src)
=> Providing reference to CLI

cli/assets/templates/zig/src/wasm4.zig
Zig has type-system support for null terminated pointers, but it isn't specified in the api right now.
=> [zig]: make string pointers null terminated

cli/assets/templates/zig/src/wasm4.zig
Support calling `text` and `trace` with non null-terminated strings, such
as formatted ones.
I'm bringing up this PR because I think this is an overlooked use case, but I could just be missing something.
While developing, there is inevitably a need to print formatted strings for debugging, so I've been using the `trace` API for this purpose. But the current version of `trace` in wasm4.zig wouldn't compile when passed formatted strings because they are not null-terminated.
Following is a demo of what I am trying to do and the compile error I get on main:
```zig
const std = @import("std");
const w4 = @import("wasm4.zig");
var buffer: [100]u8 = undefined;
var fba: std.heap.FixedBufferAllocator = undefined;
var allocator: *std.mem.Allocator = undefined;
export fn start() void {
fba = …
```
=> [zig]: support formatted strings

runtimes/web/src/index.js
I simply moved requestAnimationFrame to the end of the function. This
means the error will be encountered before the next frame is called.
Closes #196
=> Stop when on trap instructions

cli/assets/templates/nim/src/config.nims
The default code to build nim has a more prominent error message when
attempting to build without WASI_SDK_ROOT defined.
=> Adjust Nim template build code to show the issue more clearly when $WASI_SDK_ROOT is missing

cli/assets/templates/rust/src/wasm4.rs
Hides a warning when running `cargo clippy` on a Rust WASM-4 project
```
warning: this function has too many arguments (9/7)
--> src\wasm4.rs:62:1
|
62 | / pub fn blit_sub(
63 | |     sprite: &[u8],
64 | |     x: i32,
65 | |     y: i32,
...  |
71 | |     flags: u32,
72 | | ) {
| |__^
|
= note: `#[warn(clippy::too_many_arguments)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#too_many_arguments
```
=> silenced "too many arguments" clippy lint

.gitattributes, cli/assets/templates/nelua/Makefile, cli/assets/templates/nelua/src/wasm4.nelua
additionally,
- add .gitattributes for using lua as syntax highlighting on github for .nelua files
- add ``--verbose`` flag in debug builds
=> add function bindings to nelua, move cflags from Makefile to wasm4.nelua (#204)

cli/lib/png2src.js, site/docs/tutorials/snake/collision-detection.md, site/docs/tutorials/snake/drawing-the-snake.md, site/docs/tutorials/snake/handling-user-input.md, site/docs/tutorials/snake/moving-the-snake.md, site/docs/tutorials/snake/placing-the-fruit.md
- Fix Zig errors
- Adhere to Zig naming conventions https://ziglang.org/documentation/0.9.0/#Names
- Small typo in text
=> Fix Zig examples for snake tutorial

runtimes/native/src/backend/wasm_wasm3.c
This is an arbitrary limit corresponding to the implementation details
of the wasm3 interpreter. It's unrelated to the resource constraints of
the wasm4 VM. Making this too small will ultimately result in `[trap]
stack overflow` at the command line.
Using 64 KB, since this is the default of wasm3 standalone binary on
desktop platforms (from wasm3/platforms/app/main.c).
Fixes https://github.com/aduros/wasm4/issues/235
=> Increase wasm3 stack size from 4 KB to 64 KB.

cli/assets/templates/nelua/src/main.nelua, cli/assets/templates/nelua/src/wasm4.nelua, cli/lib/png2src.js, site/docs/getting-started/hello-world.md, site/docs/guides/audio.md, site/docs/guides/basic-drawing.md, site/docs/guides/saving-data.md, site/docs/guides/sprites.md, site/docs/guides/user-input.md, site/docs/reference/cli.md, site/docs/tutorials/snake/collision-detection.md, site/docs/tutorials/snake/creating-the-snake.md, site/docs/tutorials/snake/drawing-the-snake.md, site/docs/tutorials/snake/handling-user-input.md, site/docs/tutorials/snake/moving-the-snake.md, site/docs/tutorials/snake/placing-the-fruit.md, site/docs/tutorials/snake/publish-your-game.md, site/docs/tutorials/snake/setting-color-palette.md, site/docs/tutorials/snake/setup-project.md
This PR improves the nelua bindings and add the remaining documentation for the website, it's related with #204 
However, I also have a question, the bindings uses [`<comptime>` annotations](https://nelua.io/overview/#compile-time-variables), like this:
```lua
global MOUSE_LEFT <comptime> = 1
global MOUSE_RIGHT <comptime> = 2
global MOUSE_MIDDLE <comptime> = 4
```
This way, the nelua compiler generates more efficient code.
My question is, should `png2src` also emit `<comptime>` constants instead of run-time ones? Like this:
```lua
local bunny_width <comptime> = 16
local bunny_height <comptime> = 16
local bunny_flags <comptime> = 1 -- BLIT_2BPP
local bunny: [64]uint8 <const> = { --[[...]] }
```
If so, I can commit and add this change in this PR if you wish.
=> Nelua improvements

runtimes/native/src/framebuffer.c, runtimes/web/src/framebuffer.js
After investigating #228 I found that `x` was used to calculate the `shift`. I believe that using the `bitIndex` instead should result in the actual expected behavior.
=> fix blit for non-byte-aligned sprites

runtimes/web/src/apu.js
The first commit eliminates phase reset on `tone` calls if an audio channel stays in use.
Instead we only update tone properties, like time-to-release, the ADSR timings in the GainNode, and duty.
This basically merges overlapping tones, and allows for WAY smoother and more flexible audio processing.
You can test the difference in behaviour with this example program: [cart.zip](https://github.com/aduros/wasm4/files/7766442/cart.zip) Hold down X while switching through the different modes.
If you instead want the grating phase reset noise from before, you can still get that behaviour by inserting `tone` calls with duration 0 yourself.
The second commit is more subtle: If a channel was previously active, don't reset its initial gain to 0.
This allows smooth volume ramps between any two …
=> More flexible and fluid APU behaviour (web runtime APU)

cli/cli.js, cli/lib/server.js, site/docs/reference/cli.md
The new `port` option allows to specify one or more ranges for the port.
The default is a range between 4000 and 6000
A range can be specified like `4000-6000`.
A fixed port can also be specified: --port 4444
It's also possible to provide multiple ranges:
`--port 4000-6000,8000-7000,8080`
If a port is taken, it attempts to do this again.
After 10 attempts, an exception is thrown.
This Solves #198
=> Adding custom ports to run and watch

runtimes/web/src/constants.js, runtimes/web/src/index.js, runtimes/web/src/runtime.js
Adds blue screen error handling for common WASM Runtime errors.
Resolves #245
=> (enh) add blue screen for WASM Runtime errors

site/src/components/MultiLanguage.js, site/src/components/MultiLanguageCode.js
This PR adds the option to set the initial language from query params, param `code-lang`, and fixes several react related issues in `MultiLanguage.js` & `MultiLanguageCode.js`
example: https://deploy-preview-243--wasm4.netlify.app/docs/guides/saving-data/?code-lang=go#reading-data-from-disk
=> [Docs][Wasm4] optionally set initial language of MultiLanguageCode from query params

cli/assets/templates/zig/build.zig
Workaround for https://github.com/ziglang/zig/issues/2910.
See in particular:
https://github.com/ziglang/zig/issues/2910#issuecomment-1003455815
https://github.com/ziglang/zig/issues/2910#issuecomment-1003456922
=> zig template: export only the 'start' and 'update' functions

cli/assets/templates/c/Makefile, cli/assets/templates/go/Makefile, cli/assets/templates/nelua/Makefile, cli/assets/templates/wat/Makefile
If `which` cannot find the `wasm-opt` file it outputs an error message, which contains a full `PATH` printed.
It creates a lot of noise for the `make` command. The `command -v` does not print anything if the file is not found.
=> Replaced the `which` command with the `command -v` for locating `wasm-opt` in the Makefile templates

cli/assets/templates/rust/.cargo/config.toml
Updates rust template like https://github.com/aduros/wasm4/commit/87b0b01d8bfa5d6abbbe2ce29a2e6d883d2293b5 did with c template.
Also update some comments inside of the `.cargo/config.toml`
=> Update rust stack size to 8KiB

runtimes/native/src/backend/main_libretro.c
This makes it so that you after loading the WASM-4 core, the "Start Core" option isn't available until you explicitly load a game.
=> libretro: State that WASM-4 requires content to run

runtimes/web/src/constants.js, runtimes/web/src/index.js, runtimes/web/src/runtime.js
This PR fixes #273 by setting "crashed" to true after resetting the runtime. This causes the runtime not to update while the new WASM is being initialized, as per my theory in #273. Experimentally, this seems to resolve the issue.
This approach feels a little hacky, as we're semantically overloading the meaning of the "crashed" field to also mean "rebooting". Setting "paused" to true would not be as reliable, because other events on the page could still seemingly cause the runtime to unpause while it's still not ready.
A potential alternative would be to have reboot create a new runtime from scratch, avoiding any possibility of the active runtime being in an intermediate state. That may be the best approach, but I didn't implement that as it would be more refactoring and I was curious …
=> Avoid calling update while we're resetting the game

cli/lib/png2src.js
This changes the behavior of png2src. It now ignores the palette of the image and just looks at the colors that are *actually* used.
Afterwards the colors get sorted and then applied. I tested this with the images below and it seems to work as expected.
I tried the following scenarios:
1. Image with 4 colors + Transparency (5 colors in total)
2. Image with 4 colors without Transparency (4 colors in total)
3. Image with 2 colors (2 colors in total)
The first image *should* get rejected. And that is the case.
The Image with 4 colors was tested in Index and RGB mode. Both produce the same result.
This is true for the Image with 2 colors as well.
In case of 2 colors, I tried something else to disrupt the old and the new png2src: I used 4 colors in the index, but only used 2 of those colors …
=> Improved png2src

.gitmodules
The git protocol is no longer supported by github because it is insecure https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> Replaced git:// urls with https://

cli/assets/templates/zig/build.zig
Implements #297 for zig template.
Require minimal zig version of 0.9.1 or 0.10.0-dev.258 to not cause silent data corruptions.
=> Switch zig template to use --stack-first

runtimes/native/README.md
This is probably common knowledge but I wanted to build only one of the targets and began by modifying the CMakeLists.txt, but then figured out I could just add a command line flag and thought others might want to know.
In other news, I got WASM4 working on my RG351:
=> Add instructions for building specific targets

runtimes/web/src/index.js
deltaFrame was being used for the fps counter, but it is inaccurate because it does not reflect a real time. this caused the frame counter to display ~40-45fps when the actual framerate was 60fps
=> fix devtools fps counter

site/docs/guides/basic-drawing.md
Change the Rust examples in Docs > Guides > Basic Drawing to directly convert FRAMEBUFFER from a *mut to a &mut without null-checking it.
=> Directly convert FRAMEBUFFER pointer in Rust

runtimes/native/src/backend/main.c, runtimes/native/src/backend/main_libretro.c, runtimes/native/src/runtime.c, runtimes/native/src/runtime.h
Will use the `<filepath>.disk` as filename for the save disk.
When running wasm files directly, the name will become `my_game.wasm.disk`.
When running bundles, the name will become `my_game_bundle.disk` (or `my_game_bundle.exe.disk` on Windows).
This could be changed to trim the extension, but since linux doesn't use file extensions for executables, the code would vary depending on OS.
The reason for exposing the Disk struct and not simply copying the struct (like libretro does) is to make disk files not dependent on endianness (and as such transferrable between different platforms).
I otherwise kept the interface for `w4_runtimeInit` as to not break libretro main (or any others).
=> Add support for saving/loading disks to native runtime

runtimes/web/src/framebuffer.js
Solves issue #347
I noticed the issue only applied to web, and the reason was that the wrong line drawing method was being used.
Compare [native](https://github.com/aduros/wasm4/blob/5fc0583b5c0cd1e3b61a915f72c985f625da53b5/runtimes/native/src/framebuffer.c#L190L191) with [web](https://github.com/aduros/wasm4/blob/5fc0583b5c0cd1e3b61a915f72c985f625da53b5/runtimes/web/src/framebuffer.js#L185L186).
=> Fix oval drawing bug on the web runtime

cli/assets/templates/c/Makefile
Creating games using wasm4 assumes a lot of number operations.
The `-Wconversion` and `-Wsign-conversion` are added in order
to catch any subtle bugs like number overflows or casting.
=> Add the -Wconversion -Wsign-conversion flags to the Makefile template

cli/assets/templates/rust/src/wasm4.rs
This patch changes the FRAMEBUFFER and PALETTE variables in the Rust template from `pub static mut` to `pub const`, as the pointers themselves don't ever need to be mutated or have a static memory address.
In the future, we may be able to have the framebuffer directly like this:
`pub static mut FRAMEBUFFER: [u8; 6400] = unsafe { *(0xa0 as *mut [u8; 6400]) };`
but this isn't stablised yet.
=> Change Rust template static muts to consts

runtimes/native/src/backend/main_libretro.c, runtimes/native/src/framebuffer.c
* GCC 4.2 is used for osx-ppc and doesn't understand 0b syntax
* PSP hangs with threaded audio
* 16-bit graphics turned out not to be necessarry for PSP support but might be necessary in the future and good to have as a configurable alternative
=> Support for non-threaded audio, 16-bit graphics and gcc 4.2

cli/assets/bundle/template.html, cli/cli.js, cli/lib/bundle.js, runtimes/web/src/index.js, runtimes/web/src/runtime.js, site/src/components/PlayCart.js
Solves issue #357.
Runtime itself defaults to `disk`.
Bundles default to `<title>-disk` with a CLI option to manually set the prefix.
Site uses `<slug>-disk`.
=> web: Add disk localStorage prefix

examples/sound-demo/src/main.c, runtimes/native/src/apu.c, runtimes/web/src/apu.js, site/docs/guides/audio.md, site/docs/tutorials/snake/setting-color-palette.md
This adressess issue #331 
The specification is still not standard but this solution is backwards compatible.
`tone`'s volume parameter now accepts a peak volume with an 8 bit shift.
This volume is the peak volume reached at the end of the attack duration.
=> Add peak amplitude to ADSR specification

cli/assets/templates/assemblyscript/src/wasm4.ts, cli/assets/templates/c/src/wasm4.h, cli/assets/templates/d/source/wasm4.d, cli/assets/templates/go/w4/wasm4.go, cli/assets/templates/nelua/src/wasm4.nelua, cli/assets/templates/nim/src/cart/wasm4.nim, cli/assets/templates/odin/src/w4/wasm4_wasm32.odin, cli/assets/templates/rust/src/wasm4.rs, cli/assets/templates/wat/main.wat, cli/assets/templates/zig/src/wasm4.zig, examples/sound-demo/src/main.c, runtimes/native/src/apu.c, runtimes/web/src/apu-worklet.ts, runtimes/web/src/apu.js, site/docs/guides/audio.md
=> Tone panning (solves #320)

site/docs/getting-started/setup.md, site/docs/guides/distribution.md, site/docs/tutorials/snake/collision-detection.md, site/docs/tutorials/snake/placing-the-fruit.md
As I had a typo to fix in the Porth docs, i used this opportunity to run a spell checker to see if anything else could be corrected.
=> Fix some typos in the docs

cli/lib/bundle.js
Changes error message
```
Cart is above the size limit of ${limit} bytes.
```
to
```
Cart size of ${stat.size} bytes is above the limit of ${limit} bytes.
```
=> When cart is too big, the error shows how big it is.

cli/cli.js, cli/lib/bundle.js, site/docs/guides/distribution.md, site/docs/reference/cli.md
Add option `w4 build --html-template <file>`. This will specify a
Mustache template that is used when generating standalone html file.
You can use this to customize the HTML page that renders the cart.
The default template is the built-in template in cli/assets/bundle/template.html.
```html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
{{#html.metadata}}
<meta name="{{name}}" content="{{content}}">
{{/html.metadata}}
{{#html.description}}
<meta name="description" content="{{html.description}}">
{{/html.description}}
{{#html.iconUrl}}
<link rel="shortcut icon" href="{{html.iconUrl}}">
{{/html.iconUrl}}
{{#html.diskPrefix}}
<script id="wasm4-disk-prefix" …
```
=> Support defining template file for standalone HTML bundle

site/docs/getting-started/setup.md, site/docs/tutorials/snake/setup-project.md
URLs to the Odin project were prepended with an extra `https://`. This PR fixes them
=> Fix typo in Odin's URL 

runtimes/web/src/ui/app.ts
As discussed in #470.
This will warn once per gamepad (so, if somebody connects an nonstandard gamepad and then tries another one, they will get one warning for each). This needs state in form of the `gamepadUnavailableWarned` variable. I didn't really know if it belongs in `InputState` or not, I ended up putting it in but can move it out if you prefer.
Also, this is my first code in TS in my entire life, so caveat emptor :D I did test it on my gamepad and it does seem to work.
=> Add a warning when a non-standard gamepad is detected.

site/docs/guides/sprites.md
Just noticed there was a missing argument on the Porth `blit` documentation.
=> Fix porth `blit` docs

runtimes/web/src/ui/app.ts
When playing on mobile, the first touch of any button will freeze the game for a brief moment. This is very annoying for most games.
Using `touch-action: manipulation` seems to fix the delay issue.
=> Set `touch-action: manipulation` to prevent delays on mobile.

site/package-lock.json, site/package.json
Fixes giscus iframe size.
The latest version is 2.2.0, but it has a breaking change so in the meantime this version fixes the iframe sizing issue with minimal impact.
=> Update @giscus/react to v1.1.2 (fixes iframe size)

runtimes/native/src/framebuffer.c, runtimes/web/src/framebuffer.ts
With the oval fix PR #525 I settled on a less block appearance for the ovals. After it got merged, @ibillingsley commented that they were relying on the blockiness in [their game One Slime Army](https://wasm4.org/play/one-slime-army), and without it the game looks considerably worse. This PR restores the blockiness to the oval drawing.
=> Oval: restore blockiness

runtimes/native/src/util.c, runtimes/native/src/util.h
`error: cast discards const qualifier`
Doing some zig build shenanigans
There might be more warnings that need to be fixed, but this is what was required for what I'm doing now
=> Native runtime: fix const discard warning

runtimes/web/src/ui/app.ts, runtimes/web/src/ui/menu-overlay.ts
Implementation of disk importing/exporting, as initially suggested on issue #553.
Option indexes for menu overlay were moved in order to be a little easier to reorder them if necessary.
There is now a new "*Disk Options*" submenu, which includes four options:
- **Back:** return to previous menu.
- **Export disk:** download the save data to a binary file, called `<prefix>.disk`.
- **Import disk:** open a file picker, select a `.disk` file, then load a game disk.
- **Clear disk:** clear all contents of game disk.
=> Disk import/export/clear

site/docs/reference/cli.md
The docs say that `w4 run` doesn't reload the cart if cart.wasm gets updated while it's running, but it actually does!
=> Remove incorrect information from `w4 run` docs

runtimes/native/src/framebuffer.c, runtimes/web/src/framebuffer.ts
Follow-up to #561.  
I believe I figured out the discrepancy with drawOval compared to the [TIC-80 version](https://github.com/nesbox/TIC-80/blob/e58c583ea7b000446971a311d5469d0b7d90531b/src/core/draw.c#L497) used as reference.
Their parameters are an inclusive bounding box. When calculating `a` and `b` from `width` and `height` we need to subtract `1` to match their algorithm. This seems to correct the asymmetry we were seeing at certain sizes:  
@desttinghim fyi
=> Oval fix asymmetry

cli/assets/templates/rust/src/wasm4.rs, site/docs/guides/text.md, site/docs/reference/functions.md
This pull request resolves issue #590. It is an alternative/predecessor to my earlier (and more involved) pull request #528.
Unlike the other programming languages supported by WASM-4, Rust enforces that its strings (`String`, `&str` and string literals) are valid UTF-8, which prevents game developers from using `\x80` in a string literal to draw the X button. A solution would be using byte strings:
```rust
text(b"Press \x80 to jump!", 10, 10);
```
In fact pull request #573 added this code sample, but it does not compile with v2.5.3 (see #590). I had somehow convinced myself that allowing byte strings would prevent normal string literals (e.g. just `text("Hello world!", 10, 10)`) from compiling, which would have been a big loss in ergonomics for Rust users. That's why I had originally …
=> Improve Rust template to allow drawing buttons, resolving issue #590

runtimes/native/src/framebuffer.c
On web, calls to `textUtf8` and `textUtf16` [will stop at a null-terminator](https://github.com/aduros/wasm4/blob/9149980e0f8122fcfa05445baf2d253d991787dc/runtimes/web/src/framebuffer.ts#L277) even when [given a length](https://github.com/aduros/wasm4/blob/main/runtimes/web/src/runtime.ts#L198). Native does not do this, but instead will happily try to print the null character despite there being no font glyph for it.
This commit changes native to also stop at null-terminators to remove the discrepancy between the runtimes.
We could also instead change web to print out the null characters, but that doesn't serve any purpose and is less likely to be what a game creator wants.
=> Remove text null-terminator discrepancy

cli/lib/server.js, runtimes/native/src/backend/main.c
- [Fixes `w4 run` piping](https://github.com/aduros/wasm4/commit/1d1f2b7c6b1da2bce2dacdf16da64d12f0e0afc8)
- Waits for the end of the input instead of starting the server automatically without the cart.
- [Adds piping support to the native backend](https://github.com/aduros/wasm4/commit/19074ad63358cd8a72cd941623e4477c6bd024dd)
- Avaiable from both the executable and the `w4 -run-native` cli option
- Adds `-` as an alias for `/dev/stdin` for both backends.
- Both should work on windows, but was not tested
=> Improve piping support and add `-` alias.

runtimes/native/src/backend/main.c, runtimes/native/src/backend/main_libretro.c, runtimes/native/src/framebuffer.c, runtimes/native/src/runtime.c, runtimes/native/src/util.c, runtimes/native/src/util.h
These commits fix some potential null pointer dereferences, squash some compiler warnings, and defensively add a `#pragma pack(1)` to the memory layout struct.
=> General improvements to the native runtime

runtimes/web/src/netplay/index.ts
Make the invite link the same URL that the game is being displayed from with the netplay peer ID parameter, instead of a link to wasm4.org/netplay.
When bundling wasm4 games as HTML, it's an odd user experience that invite links take players off to another website.
=> Make the invite link work for html bundles

runtimes/web/src/ui/utils.ts
Current fallback for copying netplay url to clipboard does not work in safari due to restriction that it must occur within a user interaction event. Proposed solution is to create a dialog box from which the user can copy the link and then close the dialog. Added benefit is that the current fallback makes use of execCommand, which is deprecated.
=> Resolving issue with copying netplay link on safari

runtimes/web/src/ui/app.ts
When the DEV_NETPLAY flag is set to true, copyNetplayLink() is called in runtimes/web/app.ts. This sets this.netplay = true and copies the neplay url to the clipboard. However, this call to copyNetplayLink() is currently happening before the call to runtime.start(), which is only called if this.netplay == false. Since copyNetplayLink() sets this.netplay = true, this prevents runtime.start() from being called. It makes sense to avoid calls to runtim.start() by non-host players who join the game. However, it needs to be called by the host in order to perform any initial setup the game may require. Moving the check for the DEV_NETPLAY flag and the call to copyNetplayLink() after the call to runtime.start() fixes this issue.
=> proposed fix for issue #664

site/docs/tutorials/snake/collision-detection.md, site/docs/tutorials/snake/drawing-the-snake.md
Without the asterisks (`*`) I encountered some memory issues when using Zig's `std.BoundedArray`. Since I never used the language, it took me a while to figure out the problem, so I'm updating it for the future users.
=> Fix the annotations in the Zig Snake tutorial

runtimes/web/src/ui/app.ts
I think this is technically the right thing to do, just in case the wasm start function or WASI _start/_initialize functions read from memory and then set some global variables (I don't know why they would, but they could.)
Probably wouldn't be necessary if we [fixed the global variable problem](https://github.com/aduros/wasm4/issues/649), and saved them in the `State`? Although thinking about it, there's other global state like wasm tables that we should worry about.
(Aside: I think we should try to tidy up the abstraction between runtime.reset(), runtime.load() and App.resetCart() a little, they seem a bit inter-dependant.)
Sorry for the train-of-thought pull request, I just find it helpful to have things written down 😊
=> Always call runtime.reset() in App.resetCart()

devtools/web/src/devtools-manager.ts, runtimes/web/src/ui/app.ts
FIXES #681 
The correct delta time for the frame was not being passed into the devtoolsManager.updateCompleted() call. (This apparently was a known issue since there is a comment that says "FIXME(2022-08-20): Pass the correct FPS for display." This commit adds a variable to track a timestamp for the last completed frame update and passes the delta between this timestamp and the current frame timestamp into the updateCompleted() call.
The resulting displayed FPS is accurate, but can be choppy due to the intermittent frame delays that are caused by waiting for timeFrameStart to catch up to timeNextUpdate. So, to smooth this out, this commit also includes a change to devToolsManager to display a rolling 10 frame average FPS.
=> Pass correct fps to devtools

.github/workflows/build.yml, cli/lib/new.js, cli/lib/watch.js, site/docs/getting-started/setup.md, site/docs/tutorials/snake/publish-your-game.md
b19c86b15bc09c1bbdfbda3a003b92b61297d005: Fixes `w4` looking for `cart.wasm` in the wrong location since #669.
5063e90d7fc592fae5a1168cbfd19ca7473a697d: Makes the native binary compatible with linux installations older than ~2 years.
=> 2 simple fixes

cli/cli.js, cli/lib/png2src.js, site/docs/reference/cli.md
A friend and I have been working on support w4 in Roc. That project lives here: https://github.com/lukewilliamboswell/roc-wasm4/
This adds png2src support for Roc. Note, Roc does not store all flags with a sprite. Instead, roc just stores bits per pixel and leaves the rest of the flags for when calling `blit` or `blitSub`.
=> Add support for Roc in png2src

.github/workflows/build.yml, cli/README.md, cli/package-lock.json, cli/package.json, devtools/web/package-lock.json, devtools/web/package.json, devtools/web/src/components/devtools/devtools.ts, devtools/web/src/components/gamepad/gamepad.ts, devtools/web/src/components/memory-view/memory-view.ts, devtools/web/src/components/mouse-buttons/mouse-buttons.ts, devtools/web/src/components/palette/palette.ts, devtools/web/src/styles/commons.ts, devtools/web/tsconfig.json, runtimes/web/README.md, runtimes/web/package-lock.json, runtimes/web/package.json, runtimes/web/src/apu-worklet.ts, runtimes/web/src/apu.ts, runtimes/web/src/audioworklet.d.ts, runtimes/web/src/compositor.ts, runtimes/web/src/constants.ts, runtimes/web/src/devkit.ts, runtimes/web/src/runtime.ts, runtimes/web/src/ui/app.ts, runtimes/web/src/ui/utils.ts, runtimes/web/src/vite-env.d.ts, runtimes/web/tsconfig.json, runtimes/web/vite.config.ts
I updated the dependencies, most notably Vite to version 5. I also reviewed how Vite was being configured and fixed development builds being used in production.
I also fixed several typescript issues, the code now passes type-checking.
There are also various other little tidy-ups and improvements.
=> Update Dependencies, fix type errors, and general improvements.

cli/assets/templates/zig/build.zig
I'm not sure when or why these changes occurred in Zig, but with this fix I can compile the template on the latest version of Zig.
=> zig: Fix template build

runtimes/native/src/apu.c, runtimes/native/src/apu.h, runtimes/native/src/runtime.c, runtimes/web/src/apu-worklet.ts, runtimes/web/src/apu.ts, runtimes/web/src/runtime.ts
It has always been an issue that if you try to continously play `tone` each frame, you will get gaps due to frame timing issues. This has made doing live-playback or creating very fancy sounds difficult.
The previous workaround has been to extend each `tone` so that the next one will override it, but this has several drawbacks when working with pitch-bends.
What is done here is make the APU aware of WASM-4 ticks. This enables us to keep playing the active `tone` past its expiration as long as the next tick hasn't rolled in yet, thus avoiding gaps in playback.
Here is a video demonstration of the fix: [**demo**](https://github.com/aduros/wasm4/assets/3710677/34f58e2f-1d12-4a8a-ade9-6af052062b34)
This also shows that it only affects continously calling `tone` with sustain and doesn't affect …
=> ✨ Make APU tick aware ✨ 

cli/assets/templates/assemblyscript/src/wasm4.ts, cli/assets/templates/c/src/wasm4.h, cli/assets/templates/c3/cart/src/wasm4.c3, cli/assets/templates/d/source/wasm4.d, cli/assets/templates/go/w4/wasm4.go, cli/assets/templates/nelua/src/wasm4.nelua, cli/assets/templates/nim/src/cart/wasm4.nim, cli/assets/templates/odin/src/w4/wasm4_wasm32.odin, cli/assets/templates/penne/src/wasm4.pn, cli/assets/templates/rust/src/wasm4.rs, cli/assets/templates/wat/main.wat, cli/assets/templates/zig/src/wasm4.zig, runtimes/native/src/apu.c, runtimes/web/src/apu-worklet.ts, site/docs/guides/audio.md, site/docs/reference/functions.md
This is another go at #333, but with a slightly different approach from #334.
Big thanks to @marler8997 for the detailed proposal and the other PR!
Has been tested working on both web and native.
Since frequencies sent to `tone` are integers, we lose quite a bit of precision when it comes to playing lower notes. This PR implements a variant of #333 to make `tone` capable of playing MIDI notes. We have 16 bits per frequency, which is split up into 8 bits for the note, and 8 bits for optional pitch bend, as to not be limited to pure notes.
It turns out the implementation for this is very simple (JS implementation required less than 15 lines!), and since the flag is new and optional it doesn't affect any prior carts. In my opinion this feature is overdue.
Instead of calling `tone` with …
=> APU Note Mode (alternative version of #334)

runtimes/native/src/apu.c, runtimes/web/src/apu-worklet.ts, runtimes/web/src/runtime.ts
Related to #705 
I found that the triangle wave behaved incorrectly, and this was due to its specific `releaseTime` being added.
I had tested the triangle wave locally before submitting the last PR, but did so at a different sample rate so maybe that affected something, I don't know.
Here's a piece of code to test this bug with:
```zig
const w4 = @import("wasm4.zig");
export fn start() void {}
var ticks: usize = 0;
export fn update() void {
w4.DRAW_COLORS.* = 0x14;
w4.text("\x80:short attack", 5, 5);
w4.text("\x81:short decay", 5, 15);
w4.text("\x84:short sustain", 5, 25);
w4.text("\x86:long release", 5, 35);
w4.text("\x87:short sus tri", 5, 45);
w4.text("\x85:short decay tri", 5, 55);
w4.DRAW_COLORS.* = 0x13;
if (w4.GAMEPAD1.* & w4.BUTTON_1 > 0) {
w4.text("A", 5, 80);
w4.tone(60, 1 << …
```
=> apu: fix continous tone for triangle

runtimes/native/src/runtime.c, runtimes/web/src/runtime.ts
**Updated 2024-04-18!**
Using `vprintf` directly would segfault on `%s` because it would try to read the pointer from host memory rather than WASM memory.
Code is mostly ported from web runtime.
```c
#include "wasm4.h"
void start() {
tracef("|A|%%|%c|%d|0x%x|%s|%f|%u|%d|", 'B', 123, 0xcafe, "string", 1.23, 456, 789);
}
```
```diff
Old:
- Web:    |A|%|B|123|0xcafe|string|1.23||456|
- Native: |A|%%|%c|%d|0x%x|%s|%f|%u|%d|
New:
+ Web:    |A|%|B|123|0xcafe|string|1.23|%u|456|
+ Native: |A|%|B|123|0xcafe|string|1.23|%u|456|
```
The web runtime was also modified to show unrecognized specifiers as they are rather than remove them (see `%u`).
=> Add tracef to native runtime

runtimes/native/src/framebuffer.c, runtimes/web/src/framebuffer.ts
If x+width goes off-screen in the negative it would corrupt the framebuffer.
=> rect: fix bounds

cli/assets/templates/zig/.gitignore, cli/assets/templates/zig/build.zig
- `zig-cache` renamed to `.zig-cache`  
https://ziglang.org/download/0.13.0/release-notes.html#codezig-cachecode-renamed-to-codezig-cachecode
- introduce `b.path`; deprecate `LazyPath.relative` (removed in 0.13.0)
https://ziglang.org/download/0.12.0/release-notes.html#introduce-bpath-deprecate-LazyPathrelative
=> Fix Zig template for Zig 0.13.0

cli/assets/templates/nim/cart.nimble
When compiling the cart, an error occurs:
Threads not implemented for os:any. Please compile with --threads:off. stack trace: (most recent call last)
Added --threads:off flag, for successful compilation of the cart
=> compile with --threads:off Update cart.nimble

cli/lib/png2src.js
solves #497
tested on these images, for 1bpp and 2bpp:
7x7 pixels:
8x8 pixels:
=> png2src: add ability to handle any width

runtimes/web/src/runtime.ts, runtimes/web/src/state.ts, runtimes/web/src/wasm-patch.ts
Solves #649 and #542.
Tested with the cart from https://github.com/aduros/wasm4/issues/542#issuecomment-2062089238.
I understand if this is not the direction you wanna go and maybe something should be done differently, but it's a start at finally getting this fixed :)
=> netplay: patch export globals and sync them

.github/workflows/build.yml
Fixes the following error:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
=> CI: Update upload-artifact and download-artifact

.github/workflows/build.yml, .gitmodules, runtimes/native/CMakeLists.txt, runtimes/native/README.md, runtimes/native/src/backend/wasm_toywasm.c
I only tested macOS build because i have no windows/linux environment.
=> Add toywasm support

runtimes/native/CMakeLists.txt
Fixes https://github.com/aduros/wasm4/issues/768
=> Avoid errors with an old cmake used on libretro CI

runtimes/web/src/netplay/index.ts, runtimes/web/src/state.ts
See #779
Though this looks a bit ugly, it beats the alternative.
**Explanation:**
JavaScript doesn't support checking directly whether a `Global` object is mutable or not, and parsing enough WASM to determine if each global is mutable [requires being able to parse WASM expressions](https://webassembly.github.io/spec/core/syntax/modules.html#syntax-global), meaning all possible opcodes permitted in initialization and their parameters. I gave it a quick attempt still, but the amount of opcodes that you have support depends on WASM extensions (e.g. globals using reference types and vector types add more opcodes you need to be able to handle in expressions), and simply adding the ones available today doesn't feel future-proof.
I'm also fine with reverting the global patching completely, …
=>  web: safely handle immutable globals #779

runtimes/native/src/runtime.c, test/integer_overflow/blit_1bpp_overflow.wat, test/integer_overflow/blit_2bpp_overflow.wat, test/out_of_bands_memory_access/blit_1bpp.wat, test/out_of_bands_memory_access/blit_2bpp.wat, test/out_of_bands_memory_access/tracef_double.wat, test/out_of_bands_memory_access/tracef_fmt.wat, test/out_of_bands_memory_access/tracef_str.wat, test/out_of_bands_memory_access/tracef_strptr.wat
Fixes:
https://github.com/aduros/wasm4/issues/750
https://github.com/aduros/wasm4/issues/709
=> native runtime: implement memory bounds check

cli/assets/templates/zig/build.zig
Run the cart with `zig build run`.
=> zig: allow 'zig build run'

cli/assets/templates/go/target.json
Trying the `hello-world` project, running `make` using Go returns several build errors with the current `target.json` template file.
This PR fixes them by using a working template (should close issue #595).
Currently the errors are: 
```
[wasm-validator error in function 0] unexpected false: Bulk memory operations require bulk memory [--enable-bulk-memory], on
(memory.fill
(i32.const 14856)
(i32.const 0)
(i32.const 905)
)
[wasm-validator error in function 5] unexpected false: Bulk memory operations require bulk memory [--enable-bulk-memory], on
(memory.copy
(local.get $0)
(local.get $1)
(local.get $2)
)
[wasm-validator error in function 6] unexpected false: Bulk memory operations require bulk memory [--enable-bulk-memory], on
(memory.fill
(local.get $0)
(local.get $1)
(local.get $2)
) …
```
=> fix: working tinygo target.json

cli/cli.js, cli/lib/png2src.js, cli/lib/test/png2src.test.js
=> return png2src error to caller

cli/lib/png2src.js, cli/lib/test/data_ok/smile_7x7_1BPP.png, cli/lib/test/data_ok/smile_7x7_2BPP.png, cli/lib/test/data_ok/smile_8x8_1BPP.png, cli/lib/test/data_ok/smile_8x8_2BPP.png, cli/lib/test/png2src.test.js
=> process directories

devtools/web/src/components/palette/palette.ts, devtools/web/src/devtools-manager.ts, runtimes/web/src/config-constants.ts, runtimes/web/src/constants.ts, runtimes/web/src/devkit.ts, runtimes/web/src/runtime.ts, runtimes/web/src/ui/app.ts
A few patches that:
- Fix an issue with websockets when running vite
- Fix the web runtime fps counter
- Fix the web runtime devtools palette viewer
=> Devkit, devtools and developer experience improvements

.github/workflows/build.yml
Replicating the Netlify CI build step in the GitHub Action workflow to address https://github.com/aduros/wasm4/issues/810.
This way any site building failures will be visible in future PRs.
Kind of naive approach but does the job:
=> fix(site): replicate netlify CI step.

.github/workflows/build.yml
This pull request defaults the native window backend to GLFW. The current minifb/X11 build, while functional on Wayland via XWayland, has some issues (namely the wayland fractional scale fiasco).
By building with glfw it uses the native wayland API on wayland and the Xorg API on X11. I've tested successfully in the following platforms:
Fedora Rawhide (43 pre-release) [pure wayland]
openSUSE LEAP 15.6 [x11]
Ubuntu 24.10 [wayland + xwayland]
=> Use gflw as default for the window backend

runtimes/native/src/backend/main.c
bail out gracefully when we failed to open argv[0]. note that argv[0] is not necessarily an open-able path.
=> native runtime: fix a NULL dereference
